server:
  port: 8081
spring:
  datasource:
    druid:
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.116.129:3306/mybatis?allowMultiQueries=true
        username: root
        password: root
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@192.168.116.129:1521/orcl
        username: c##mybatis
        password: mybatis

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qinh.multidatasource.entity

#showSql
logging:
  level:
    com:
      qinh:
        multidatasource:
          dao: debug


